In [3]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.svm import LinearSVR, SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

import warnings
warnings.filterwarnings(action='ignore')

In [4]:
data = pd.read_csv('delhi.csv')

In [5]:
data

,Area,BHK,Bathroom,Furnishing,Locality,Parking,Price,Status,Transaction,Type,Per_Sqft
0,800.0,3,2.0,Semi-Furnished,Rohini Sector 25,1.0,6500000,Ready_to_move,New_Property,Builder_Floor,NaN
1,750.0,2,2.0,Semi-Furnished,"J R Designers Floors, Rohini Sector 24",1.0,5000000,Ready_to_move,New_Property,Apartment,6667.0
2,950.0,2,2.0,Furnished,"Citizen Apartment, Rohini Sector 13",1.0,15500000,Ready_to_move,Resale,Apartment,6667.0
3,600.0,2,2.0,Semi-Furnished,Rohini Sector 24,1.0,4200000,Ready_to_move,Resale,Builder_Floor,6667.0
4,650.0,2,2.0,Semi-Furnished,Rohini Sector 24 carpet area 650 sqft status R...,1.0,6200000,Ready_to_move,New_Property,Builder_Floor,6667.0
...,...,...,...,...,...,...,...,...,...,...,...
1254,4118.0,4,5.0,Unfurnished,Chittaranjan Park,3.0,55000000,Ready_to_move,New_Property,Builder_Floor,12916.0
1255,1050.0,3,2.0,Semi-Furnished,Chittaranjan Park,3.0,12500000,Ready_to_move,Resale,Builder_Floor,12916.0
1256,875.0,3,3.0,Semi-Furnished,Chittaranjan Park,3.0,17500000,Ready_to_move,New_Property,Builder_Floor,12916.0
1257,990.0,2,2.0,Unfurnished,Chittaranjan Park Block A,1.0,11500000,Ready_to_move,Resale,Builder_Floor,12916.0
1258,11050.0,3,3.0,Unfurnished,Chittaranjan Park,1.0,18500000,Ready_to_move,New_Property,Builder_Floor,12916.0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Area         1259 non-null   float64
 1   BHK          1259 non-null   int64
 2   Bathroom     1257 non-null   float64
 3   Furnishing   1254 non-null   object
 4   Locality     1259 non-null   object
 5   Parking      1226 non-null   float64
 6   Price        1259 non-null   int64
 7   Status       1259 non-null   object
 8   Transaction  1259 non-null   object
 9   Type         1254 non-null   object
 10  Per_Sqft     1018 non-null   float64
dtypes: float64(4), int64(2), object(5)
memory usage: 108.3+ KB

Preprocessing

In [8]:
def onehot_encode(df, column, rename=False):
    df = df.copy()
    if rename == True:
        df[column] = df[column].replace({x: i for i, x in enumerate(df[column].unique())})
    dummies = pd.get_dummies(df[column], prefix=column)
    df = pd.concat([df, dummies], axis=1)
    df = df.drop(column, axis=1)
    return df

In [7]:

def preprocess_inputs(df):
    df = df.copy()
    
    # Drop Per_Sqft column
    df = df.drop('Per_Sqft', axis=1)
    
    # Fill missing values
    for column in ['Bathroom', 'Parking', 'Type']:
        df[column] = df[column].fillna(df[column].mode()[0])
    
    # Binary encoding
    df['Status'] = df['Status'].replace({
        'Almost_ready': 0,
        'Ready_to_move': 1
    })
    df['Transaction'] = df['Transaction'].replace({
        'New_Property': 0,
        'Resale': 1
    })
    df['Type'] = df['Type'].replace({
        'Builder_Floor': 0,
        'Apartment': 1
    })
    
    # One-hot encoding
    df = onehot_encode(df, column='Furnishing', rename=False)
    df = onehot_encode(df, column='Locality', rename=True)
    
    # Split df into X and y
    y = df['Price']
    X = df.drop('Price', axis=1)
    
    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, shuffle=True, random_state=1)
    
    # Scale X
    scaler = StandardScaler()
    scaler.fit(X_train)
    X_train = pd.DataFrame(scaler.transform(X_train), index=X_train.index, columns=X_train.columns)
    X_test = pd.DataFrame(scaler.transform(X_test), index=X_test.index, columns=X_test.columns)
    
    return X_train, X_test, y_train, y_test

In [9]:
X_train, X_test, y_train, y_test = preprocess_inputs(data)

In [11]:
X_train

,Area,BHK,Bathroom,Parking,Status,Transaction,Type,Furnishing_Furnished,Furnishing_Semi-Furnished,Furnishing_Unfurnished,...,Locality_355,Locality_356,Locality_357,Locality_358,Locality_359,Locality_360,Locality_361,Locality_362,Locality_363,Locality_364
582,1.241514,1.245726,1.397555,-0.216906,0.245293,0.779528,-0.963219,-0.412294,0.872926,-0.631199,...,-0.058454,-0.03371,0.0,0.0,-0.144421,0.0,-0.03371,-0.03371,-0.03371,-0.03371
976,0.006189,0.198508,-0.550619,-0.216906,0.245293,0.779528,1.038186,2.425451,-1.145572,-0.631199,...,-0.058454,-0.03371,0.0,0.0,-0.144421,0.0,-0.03371,-0.03371,-0.03371,-0.03371
886,-0.748732,-1.895929,-1.524706,-0.216906,0.245293,-1.282827,1.038186,-0.412294,-1.145572,1.584285,...,-0.058454,-0.03371,0.0,0.0,-0.144421,0.0,-0.03371,-0.03371,-0.03371,-0.03371
561,0.177762,0.198508,0.423468,0.127408,0.245293,0.779528,-0.963219,-0.412294,0.872926,-0.631199,...,-0.058454,-0.03371,0.0,0.0,-0.144421,0.0,-0.03371,-0.03371,-0.03371,-0.03371
1083,-0.587454,-0.848710,-0.550619,-0.216906,0.245293,0.779528,-0.963219,-0.412294,0.872926,-0.631199,...,-0.058454,-0.03371,0.0,0.0,-0.144421,0.0,-0.03371,-0.03371,-0.03371,-0.03371
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,-0.165384,-0.848710,-0.550619,-0.216906,0.245293,0.779528,1.038186,-0.412294,-1.145572,1.584285,...,-0.058454,-0.03371,0.0,0.0,-0.144421,0.0,-0.03371,-0.03371,-0.03371,-0.03371
905,1.069941,1.245726,1.397555,0.127408,0.245293,-1.282827,-0.963219,-0.412294,-1.145572,1.584285,...,-0.058454,-0.03371,0.0,0.0,-0.144421,0.0,-0.03371,-0.03371,-0.03371,-0.03371
1096,-0.371272,-0.848710,-0.550619,0.127408,0.245293,-1.282827,-0.963219,-0.412294,-1.145572,1.584285,...,-0.058454,-0.03371,0.0,0.0,-0.144421,0.0,-0.03371,-0.03371,-0.03371,-0.03371
235,0.074818,1.245726,0.423468,-0.216906,0.245293,-1.282827,-0.963219,-0.412294,0.872926,-0.631199,...,-0.058454,-0.03371,0.0,0.0,-0.144421,0.0,-0.03371,-0.03371,-0.03371,-0.03371
1061,-0.371272,0.198508,-0.550619,-0.216906,0.245293,0.779528,-0.963219,-0.412294,-1.145572,1.584285,...,-0.058454,-0.03371,0.0,0.0,-0.144421,0.0,-0.03371,-0.03371,-0.03371,-0.03371

In [12]:
y_train

582     55000000
976     14000000
886      1490000
561     30000000
1083     4000000
          ...
715     14300000
905     67000000
1096     5500000
235     13000000
1061     8000000
Name: Price, Length: 881, dtype: int64

Tranning

In [13]:
models = {
    "                     Linear Regression": LinearRegression(),
    " Linear Regression (L2 Regularization)": Ridge(),
    " Linear Regression (L1 Regularization)": Lasso(),
    "                   K-Nearest Neighbors": KNeighborsRegressor(),
    "                        Neural Network": MLPRegressor(),
    "Support Vector Machine (Linear Kernel)": LinearSVR(),
    "   Support Vector Machine (RBF Kernel)": SVR(),
    "                         Decision Tree": DecisionTreeRegressor(),
    "                         Random Forest": RandomForestRegressor(),
    "                     Gradient Boosting": GradientBoostingRegressor(),
    "                               XGBoost": XGBRegressor(),
    "                              LightGBM": LGBMRegressor(),
    "                              CatBoost": CatBoostRegressor(verbose=0)
}

for name, model in models.items():
    model.fit(X_train, y_train)
    print(name + " trained.")

                     Linear Regression trained.
 Linear Regression (L2 Regularization) trained.
 Linear Regression (L1 Regularization) trained.
                   K-Nearest Neighbors trained.
                        Neural Network trained.
Support Vector Machine (Linear Kernel) trained.
   Support Vector Machine (RBF Kernel) trained.
                         Decision Tree trained.
                         Random Forest trained.
                     Gradient Boosting trained.
                               XGBoost trained.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000534 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 170
[LightGBM] [Info] Number of data points in the train set: 881, number of used features: 13
[LightGBM] [Info] Start training from score 20935561.861521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
                              LightGBM trained.
                              CatBoost trained.

Result

In [14]:
for name, model in models.items():
    print(name + " R^2 Score: {:.5f}".format(model.score(X_test, y_test)))

                     Linear Regression R^2 Score: 0.67648
 Linear Regression (L2 Regularization) R^2 Score: 0.67672
 Linear Regression (L1 Regularization) R^2 Score: 0.67647
                   K-Nearest Neighbors R^2 Score: 0.59447
                        Neural Network R^2 Score: -0.62240
Support Vector Machine (Linear Kernel) R^2 Score: -0.62248
   Support Vector Machine (RBF Kernel) R^2 Score: -0.07453
                         Decision Tree R^2 Score: 0.69394
                         Random Forest R^2 Score: 0.82702
                     Gradient Boosting R^2 Score: 0.83497
                               XGBoost R^2 Score: 0.87506
                              LightGBM R^2 Score: 0.77550
                              CatBoost R^2 Score: 0.85818

In [15]:
import joblib

# Suppose your best model is called best_model
best_model = CatBoostRegressor()
best_model.fit(X_train, y_train)

# Save the trained model
joblib.dump(best_model, "realty_price_model.pkl")
print("✅ Model saved as realty_price_model.pkl")

Learning rate set to 0.040132
0:	learn: 23832631.3138262	total: 3.72ms	remaining: 3.71s
1:	learn: 23268954.3658457	total: 4.35ms	remaining: 2.17s
2:	learn: 22757665.6771622	total: 4.89ms	remaining: 1.62s
3:	learn: 22333053.5004316	total: 5.41ms	remaining: 1.35s
4:	learn: 21803225.8773525	total: 5.92ms	remaining: 1.18s
5:	learn: 21318570.2308929	total: 6.46ms	remaining: 1.07s
6:	learn: 20884838.2577064	total: 7.07ms	remaining: 1s
7:	learn: 20455454.4812221	total: 7.62ms	remaining: 945ms
8:	learn: 20055311.2093293	total: 8.12ms	remaining: 894ms
9:	learn: 19677197.3193791	total: 8.66ms	remaining: 858ms
10:	learn: 19252608.7083792	total: 9.16ms	remaining: 823ms
11:	learn: 18943672.6058570	total: 9.66ms	remaining: 795ms
12:	learn: 18637506.3328346	total: 10.2ms	remaining: 774ms
13:	learn: 18272745.3832690	total: 10.7ms	remaining: 755ms
14:	learn: 17937163.9004424	total: 11.3ms	remaining: 739ms
15:	learn: 17631882.6124539	total: 11.8ms	remaining: 728ms
16:	learn: 17296702.2618454	total: 13.4ms	remaining: 776ms
17:	learn: 16970449.0662414	total: 14ms	remaining: 762ms
18:	learn: 16684545.1604713	total: 14.5ms	remaining: 751ms
19:	learn: 16415901.3895670	total: 15.2ms	remaining: 743ms
20:	learn: 16173557.5067897	total: 15.9ms	remaining: 740ms
21:	learn: 15926622.4955657	total: 16.5ms	remaining: 731ms
22:	learn: 15643014.9954699	total: 17.1ms	remaining: 725ms
23:	learn: 15402198.6716482	total: 17.9ms	remaining: 729ms
24:	learn: 15194888.9554344	total: 18.6ms	remaining: 727ms
25:	learn: 15015351.3738360	total: 19.3ms	remaining: 723ms
26:	learn: 14813277.9714633	total: 20ms	remaining: 719ms
27:	learn: 14611370.5958199	total: 20.4ms	remaining: 709ms
28:	learn: 14417346.7446797	total: 20.9ms	remaining: 700ms
29:	learn: 14248462.5387338	total: 21.5ms	remaining: 695ms
30:	learn: 14062052.3589919	total: 22ms	remaining: 688ms
31:	learn: 13907666.0418593	total: 22.5ms	remaining: 682ms
32:	learn: 13758495.1301770	total: 23.1ms	remaining: 676ms
33:	learn: 13561645.6562269	total: 23.5ms	remaining: 669ms
34:	learn: 13403616.8079612	total: 24ms	remaining: 663ms
35:	learn: 13232150.6699715	total: 24.6ms	remaining: 658ms
36:	learn: 13091265.9922844	total: 25.1ms	remaining: 653ms
37:	learn: 12951734.7183980	total: 25.6ms	remaining: 648ms
38:	learn: 12806026.2318848	total: 26.1ms	remaining: 644ms
39:	learn: 12671056.4996046	total: 26.6ms	remaining: 640ms
40:	learn: 12546002.3179457	total: 27.1ms	remaining: 635ms
41:	learn: 12418660.1867093	total: 27.6ms	remaining: 630ms
42:	learn: 12318560.4151074	total: 28.1ms	remaining: 626ms
43:	learn: 12223321.3396238	total: 28.6ms	remaining: 622ms
44:	learn: 12085831.1760035	total: 29.2ms	remaining: 619ms
45:	learn: 11972261.8483249	total: 29.7ms	remaining: 616ms
46:	learn: 11847176.4181429	total: 30.2ms	remaining: 612ms
47:	learn: 11757712.3517299	total: 30.6ms	remaining: 608ms
48:	learn: 11655550.8722212	total: 31.2ms	remaining: 605ms
49:	learn: 11549274.4280340	total: 31.8ms	remaining: 605ms
50:	learn: 11459996.6114747	total: 32.3ms	remaining: 602ms
51:	learn: 11369191.8450314	total: 32.9ms	remaining: 599ms
52:	learn: 11268464.3852910	total: 33.4ms	remaining: 597ms
53:	learn: 11186633.8032636	total: 33.9ms	remaining: 594ms
54:	learn: 11125936.4953872	total: 34.4ms	remaining: 592ms
55:	learn: 11047866.7971478	total: 34.9ms	remaining: 589ms
56:	learn: 10965395.5297969	total: 35.5ms	remaining: 587ms
57:	learn: 10900458.4674527	total: 36.1ms	remaining: 586ms
58:	learn: 10830186.4503365	total: 36.6ms	remaining: 584ms
59:	learn: 10771890.1521381	total: 37.1ms	remaining: 582ms
60:	learn: 10697668.9964119	total: 37.6ms	remaining: 579ms
61:	learn: 10635486.2929238	total: 38.1ms	remaining: 577ms
62:	learn: 10568040.5346477	total: 38.7ms	remaining: 575ms
63:	learn: 10509339.7714445	total: 39.2ms	remaining: 573ms
64:	learn: 10438129.3031511	total: 39.7ms	remaining: 571ms
65:	learn: 10370509.3184665	total: 40.2ms	remaining: 568ms
66:	learn: 10316046.6222475	total: 40.6ms	remaining: 566ms
67:	learn: 10250762.0757128	total: 41.1ms	remaining: 563ms
68:	learn: 10223954.9791629	total: 41.7ms	remaining: 562ms
69:	learn: 10181094.9470362	total: 42.1ms	remaining: 560ms
70:	learn: 10137151.4591300	total: 42.6ms	remaining: 557ms
71:	learn: 10093193.4689442	total: 43.1ms	remaining: 555ms
72:	learn: 10073080.0737147	total: 43.6ms	remaining: 553ms
73:	learn: 10017351.5469492	total: 44.1ms	remaining: 551ms
74:	learn: 9955980.3187857	total: 44.5ms	remaining: 549ms
75:	learn: 9945397.4965353	total: 45ms	remaining: 547ms
76:	learn: 9887629.4042648	total: 45.5ms	remaining: 546ms
77:	learn: 9850422.2217548	total: 46ms	remaining: 544ms
78:	learn: 9792656.4494131	total: 46.5ms	remaining: 542ms
79:	learn: 9760612.2339003	total: 46.9ms	remaining: 540ms
80:	learn: 9740389.5859620	total: 47.4ms	remaining: 538ms
81:	learn: 9681825.1088073	total: 47.9ms	remaining: 536ms
82:	learn: 9651563.2518313	total: 48.3ms	remaining: 534ms
83:	learn: 9613864.5773558	total: 48.8ms	remaining: 533ms
84:	learn: 9576436.9167688	total: 49.3ms	remaining: 531ms
85:	learn: 9554224.9418060	total: 49.8ms	remaining: 529ms
86:	learn: 9510741.8880908	total: 50.3ms	remaining: 528ms
87:	learn: 9480395.4299710	total: 50.8ms	remaining: 526ms
88:	learn: 9443959.1859476	total: 51.3ms	remaining: 525ms
89:	learn: 9406469.2899658	total: 51.8ms	remaining: 523ms
90:	learn: 9368589.7427722	total: 52.3ms	remaining: 522ms
91:	learn: 9321800.1633013	total: 52.8ms	remaining: 521ms
92:	learn: 9283880.7042744	total: 53.2ms	remaining: 519ms
93:	learn: 9247542.2235154	total: 53.7ms	remaining: 518ms
94:	learn: 9205997.1868815	total: 54.2ms	remaining: 516ms
95:	learn: 9170054.4488248	total: 54.7ms	remaining: 515ms
96:	learn: 9153279.5785258	total: 55.2ms	remaining: 514ms
97:	learn: 9130622.2805348	total: 55.7ms	remaining: 513ms
98:	learn: 9105966.9916490	total: 56.2ms	remaining: 512ms
99:	learn: 9088907.9178859	total: 56.7ms	remaining: 510ms
100:	learn: 9068086.3444770	total: 57.2ms	remaining: 509ms
101:	learn: 9034268.4998230	total: 57.7ms	remaining: 508ms
102:	learn: 9004335.5621930	total: 58.1ms	remaining: 506ms
103:	learn: 8995345.4273624	total: 58.6ms	remaining: 505ms
104:	learn: 8969120.7163559	total: 59.1ms	remaining: 504ms
105:	learn: 8946231.1667233	total: 59.6ms	remaining: 502ms
106:	learn: 8911116.4090322	total: 60.1ms	remaining: 501ms
107:	learn: 8890380.9019737	total: 60.6ms	remaining: 500ms
108:	learn: 8867159.8299135	total: 61.1ms	remaining: 500ms
109:	learn: 8860419.2754336	total: 61.6ms	remaining: 498ms
110:	learn: 8842346.7498031	total: 62.1ms	remaining: 498ms
111:	learn: 8819079.2123440	total: 62.6ms	remaining: 497ms
112:	learn: 8794197.6111116	total: 63.1ms	remaining: 496ms
113:	learn: 8775381.4386461	total: 63.6ms	remaining: 494ms
114:	learn: 8761472.8751675	total: 64.1ms	remaining: 493ms
115:	learn: 8743006.8974294	total: 64.6ms	remaining: 492ms
116:	learn: 8713025.4438777	total: 65.1ms	remaining: 491ms
117:	learn: 8688160.3959588	total: 65.6ms	remaining: 490ms
118:	learn: 8682048.0371931	total: 65.8ms	remaining: 488ms
119:	learn: 8664903.0928486	total: 66.3ms	remaining: 486ms
120:	learn: 8643441.8593195	total: 66.8ms	remaining: 485ms
121:	learn: 8640661.4487527	total: 67ms	remaining: 482ms
122:	learn: 8615571.1250089	total: 67.5ms	remaining: 481ms
123:	learn: 8606330.6945400	total: 67.9ms	remaining: 480ms
124:	learn: 8577183.9861689	total: 68.4ms	remaining: 479ms
125:	learn: 8552176.4928940	total: 68.9ms	remaining: 478ms
126:	learn: 8534561.9416766	total: 69.4ms	remaining: 477ms
127:	learn: 8512101.0502864	total: 69.9ms	remaining: 476ms
128:	learn: 8494603.1969992	total: 70.4ms	remaining: 475ms
129:	learn: 8479687.1050425	total: 70.8ms	remaining: 474ms
130:	learn: 8471231.9421592	total: 71.4ms	remaining: 473ms
131:	learn: 8454885.1718747	total: 71.8ms	remaining: 472ms
132:	learn: 8443299.7523701	total: 72.3ms	remaining: 471ms
133:	learn: 8427320.9492606	total: 72.8ms	remaining: 470ms
134:	learn: 8422435.8544070	total: 73.3ms	remaining: 470ms
135:	learn: 8406785.5057770	total: 73.8ms	remaining: 469ms
136:	learn: 8392385.0676526	total: 74.3ms	remaining: 468ms
137:	learn: 8378656.1043300	total: 74.7ms	remaining: 467ms
138:	learn: 8366173.9442512	total: 75.2ms	remaining: 466ms
139:	learn: 8358839.5969989	total: 75.7ms	remaining: 465ms
140:	learn: 8350559.7253194	total: 76.2ms	remaining: 464ms
141:	learn: 8340224.7852349	total: 76.6ms	remaining: 463ms
142:	learn: 8332893.3142309	total: 77.4ms	remaining: 464ms
143:	learn: 8318063.6588411	total: 77.9ms	remaining: 463ms
144:	learn: 8313342.2444668	total: 78.4ms	remaining: 462ms
145:	learn: 8299032.9759045	total: 79ms	remaining: 462ms
146:	learn: 8288626.1621150	total: 79.6ms	remaining: 462ms
147:	learn: 8280552.3680055	total: 80.1ms	remaining: 461ms
148:	learn: 8271495.8422562	total: 80.6ms	remaining: 460ms
149:	learn: 8264085.4430999	total: 81.1ms	remaining: 460ms
150:	learn: 8243414.2055063	total: 81.6ms	remaining: 459ms
151:	learn: 8234064.1808376	total: 82.1ms	remaining: 458ms
152:	learn: 8211910.3914931	total: 82.6ms	remaining: 457ms
153:	learn: 8201331.9918716	total: 83ms	remaining: 456ms
154:	learn: 8196515.1975413	total: 83.5ms	remaining: 455ms
155:	learn: 8173915.3532027	total: 84ms	remaining: 455ms
156:	learn: 8166384.2478893	total: 84.6ms	remaining: 454ms
157:	learn: 8153883.7080955	total: 85.1ms	remaining: 454ms
158:	learn: 8149508.0538250	total: 85.7ms	remaining: 453ms
159:	learn: 8134162.8784591	total: 86.1ms	remaining: 452ms
160:	learn: 8125796.1337628	total: 86.7ms	remaining: 452ms
161:	learn: 8107577.4684661	total: 87.2ms	remaining: 451ms
162:	learn: 8089921.0097215	total: 87.8ms	remaining: 451ms
163:	learn: 8079522.1331009	total: 88.4ms	remaining: 451ms
164:	learn: 8067164.4881816	total: 88.9ms	remaining: 450ms
165:	learn: 8055068.5503347	total: 89.3ms	remaining: 449ms
166:	learn: 8039156.2988898	total: 89.8ms	remaining: 448ms
167:	learn: 8021383.2434404	total: 90.3ms	remaining: 447ms
168:	learn: 8013824.7833308	total: 90.8ms	remaining: 446ms
169:	learn: 7997570.3168444	total: 91.3ms	remaining: 446ms
170:	learn: 7989343.3904258	total: 91.9ms	remaining: 446ms
171:	learn: 7964999.8802741	total: 92.4ms	remaining: 445ms
172:	learn: 7960460.3625420	total: 92.9ms	remaining: 444ms
173:	learn: 7949876.5842931	total: 93.4ms	remaining: 443ms
174:	learn: 7933927.4705277	total: 93.9ms	remaining: 443ms
175:	learn: 7906659.3436297	total: 94.4ms	remaining: 442ms
176:	learn: 7893594.4396051	total: 94.9ms	remaining: 441ms
177:	learn: 7883139.5807175	total: 95.4ms	remaining: 441ms
178:	learn: 7875409.7534832	total: 95.9ms	remaining: 440ms
179:	learn: 7866831.0813083	total: 96.4ms	remaining: 439ms
180:	learn: 7858945.3633641	total: 96.9ms	remaining: 438ms
181:	learn: 7848009.3073442	total: 97.4ms	remaining: 438ms
182:	learn: 7840382.3960838	total: 97.8ms	remaining: 437ms
183:	learn: 7835645.9101988	total: 98.3ms	remaining: 436ms
184:	learn: 7829919.4642308	total: 98.7ms	remaining: 435ms
185:	learn: 7808731.8767190	total: 99.2ms	remaining: 434ms
186:	learn: 7791049.4659406	total: 99.7ms	remaining: 434ms
187:	learn: 7777605.5337541	total: 100ms	remaining: 433ms
188:	learn: 7768681.1194268	total: 101ms	remaining: 433ms
189:	learn: 7755962.9201277	total: 101ms	remaining: 432ms
190:	learn: 7750285.3034686	total: 102ms	remaining: 431ms
191:	learn: 7731151.7023025	total: 102ms	remaining: 431ms
192:	learn: 7725127.9415776	total: 103ms	remaining: 430ms
193:	learn: 7706295.5811551	total: 103ms	remaining: 429ms
194:	learn: 7701078.1786673	total: 104ms	remaining: 429ms
195:	learn: 7678088.4894992	total: 104ms	remaining: 428ms
196:	learn: 7656880.4405772	total: 105ms	remaining: 427ms
197:	learn: 7651763.2807477	total: 105ms	remaining: 427ms
198:	learn: 7646412.6523537	total: 106ms	remaining: 426ms
199:	learn: 7637243.9307703	total: 106ms	remaining: 425ms
200:	learn: 7630704.4240201	total: 107ms	remaining: 424ms
201:	learn: 7625625.3582629	total: 107ms	remaining: 424ms
202:	learn: 7611795.6454498	total: 108ms	remaining: 423ms
203:	learn: 7600552.6792276	total: 108ms	remaining: 422ms
204:	learn: 7585952.4637928	total: 109ms	remaining: 421ms
205:	learn: 7580081.5584957	total: 109ms	remaining: 421ms
206:	learn: 7553673.6340019	total: 110ms	remaining: 420ms
207:	learn: 7548200.4188309	total: 110ms	remaining: 420ms
208:	learn: 7542677.1574541	total: 111ms	remaining: 420ms
209:	learn: 7536995.0729249	total: 111ms	remaining: 419ms
210:	learn: 7515821.8724608	total: 112ms	remaining: 419ms
211:	learn: 7509578.8166952	total: 113ms	remaining: 418ms
212:	learn: 7503881.1292579	total: 113ms	remaining: 418ms
213:	learn: 7486941.5481615	total: 114ms	remaining: 417ms
214:	learn: 7481794.5450116	total: 114ms	remaining: 417ms
215:	learn: 7467954.8044107	total: 115ms	remaining: 417ms
216:	learn: 7452012.4400945	total: 115ms	remaining: 416ms
217:	learn: 7431709.2701295	total: 116ms	remaining: 416ms
218:	learn: 7426206.3516271	total: 116ms	remaining: 415ms
219:	learn: 7407779.1066886	total: 117ms	remaining: 415ms
220:	learn: 7392528.6054488	total: 118ms	remaining: 414ms
221:	learn: 7375396.8769463	total: 118ms	remaining: 414ms
222:	learn: 7361371.7699866	total: 119ms	remaining: 413ms
223:	learn: 7356447.2604808	total: 119ms	remaining: 413ms
224:	learn: 7341660.7057341	total: 120ms	remaining: 413ms
225:	learn: 7330917.0886136	total: 120ms	remaining: 412ms
226:	learn: 7326012.0170262	total: 121ms	remaining: 411ms
227:	learn: 7310523.2522410	total: 121ms	remaining: 411ms
228:	learn: 7298237.3835228	total: 122ms	remaining: 410ms
229:	learn: 7293008.8363923	total: 122ms	remaining: 410ms
230:	learn: 7279522.7010548	total: 123ms	remaining: 409ms
231:	learn: 7275634.3854935	total: 123ms	remaining: 409ms
232:	learn: 7261331.0002773	total: 124ms	remaining: 408ms
233:	learn: 7247307.9564201	total: 125ms	remaining: 408ms
234:	learn: 7241774.7080497	total: 125ms	remaining: 407ms
235:	learn: 7228976.9454018	total: 126ms	remaining: 407ms
236:	learn: 7223491.0641122	total: 126ms	remaining: 406ms
237:	learn: 7210974.9241140	total: 127ms	remaining: 406ms
238:	learn: 7206055.5579860	total: 127ms	remaining: 405ms
239:	learn: 7202191.8886260	total: 128ms	remaining: 404ms
240:	learn: 7197826.9155982	total: 128ms	remaining: 404ms
241:	learn: 7186966.9229144	total: 129ms	remaining: 403ms
242:	learn: 7182771.9130223	total: 129ms	remaining: 403ms
243:	learn: 7176904.3942247	total: 130ms	remaining: 402ms
244:	learn: 7164934.0447753	total: 130ms	remaining: 402ms
245:	learn: 7153400.6078498	total: 131ms	remaining: 401ms
246:	learn: 7140528.5451136	total: 131ms	remaining: 401ms
247:	learn: 7125105.8673542	total: 132ms	remaining: 400ms
248:	learn: 7120459.2468165	total: 133ms	remaining: 400ms
249:	learn: 7116267.4485340	total: 133ms	remaining: 399ms
250:	learn: 7112158.2430850	total: 134ms	remaining: 399ms
251:	learn: 7099322.1445500	total: 134ms	remaining: 398ms
252:	learn: 7095815.8736441	total: 135ms	remaining: 398ms
253:	learn: 7089715.8875434	total: 135ms	remaining: 398ms
254:	learn: 7084207.2316923	total: 136ms	remaining: 397ms
255:	learn: 7080412.7966813	total: 137ms	remaining: 397ms
256:	learn: 7076702.6894078	total: 137ms	remaining: 396ms
257:	learn: 7064425.0709071	total: 138ms	remaining: 396ms
258:	learn: 7059628.1978535	total: 138ms	remaining: 395ms
259:	learn: 7056026.0360108	total: 139ms	remaining: 395ms
260:	learn: 7042588.4445178	total: 139ms	remaining: 394ms
261:	learn: 7032563.2832605	total: 140ms	remaining: 394ms
262:	learn: 7029055.2871015	total: 140ms	remaining: 393ms
263:	learn: 7025572.7299321	total: 141ms	remaining: 393ms
264:	learn: 7013278.4339596	total: 141ms	remaining: 392ms
265:	learn: 7006451.7623236	total: 142ms	remaining: 392ms
266:	learn: 7002696.1026452	total: 142ms	remaining: 391ms
267:	learn: 6999336.8297576	total: 143ms	remaining: 391ms
268:	learn: 6994289.0225498	total: 144ms	remaining: 390ms
269:	learn: 6991001.4362613	total: 144ms	remaining: 389ms
270:	learn: 6987448.3455781	total: 145ms	remaining: 389ms
271:	learn: 6984343.0941211	total: 145ms	remaining: 388ms
272:	learn: 6979293.8009977	total: 146ms	remaining: 388ms
273:	learn: 6976208.4052286	total: 146ms	remaining: 388ms
274:	learn: 6969000.0182309	total: 147ms	remaining: 387ms
275:	learn: 6966115.1146984	total: 148ms	remaining: 387ms
276:	learn: 6963139.3605347	total: 148ms	remaining: 387ms
277:	learn: 6954085.8715931	total: 149ms	remaining: 386ms
278:	learn: 6951297.6261261	total: 149ms	remaining: 386ms
279:	learn: 6946692.1070826	total: 150ms	remaining: 386ms
280:	learn: 6943932.7457598	total: 151ms	remaining: 385ms
281:	learn: 6932689.0501868	total: 151ms	remaining: 385ms
282:	learn: 6923780.0102564	total: 152ms	remaining: 385ms
283:	learn: 6920957.7703331	total: 152ms	remaining: 384ms
284:	learn: 6910651.8989380	total: 153ms	remaining: 384ms
285:	learn: 6900772.0698680	total: 154ms	remaining: 384ms
286:	learn: 6888193.1732019	total: 154ms	remaining: 383ms
287:	learn: 6883537.1868673	total: 155ms	remaining: 383ms
288:	learn: 6864869.7748652	total: 156ms	remaining: 383ms
289:	learn: 6858806.4797345	total: 156ms	remaining: 382ms
290:	learn: 6848491.1045798	total: 157ms	remaining: 382ms
291:	learn: 6832817.9674627	total: 158ms	remaining: 382ms
292:	learn: 6827594.3078424	total: 158ms	remaining: 382ms
293:	learn: 6824797.0872651	total: 159ms	remaining: 381ms
294:	learn: 6820628.9168891	total: 159ms	remaining: 381ms
295:	learn: 6816020.1156399	total: 160ms	remaining: 380ms
296:	learn: 6799062.4653755	total: 161ms	remaining: 380ms
297:	learn: 6790368.3624149	total: 161ms	remaining: 380ms
298:	learn: 6780731.3574244	total: 162ms	remaining: 380ms
299:	learn: 6776510.2220410	total: 162ms	remaining: 379ms
300:	learn: 6768162.9556270	total: 163ms	remaining: 379ms
301:	learn: 6760134.6257259	total: 164ms	remaining: 378ms
302:	learn: 6752858.1053255	total: 164ms	remaining: 378ms
303:	learn: 6743638.2516010	total: 165ms	remaining: 378ms
304:	learn: 6738993.8277303	total: 166ms	remaining: 377ms
305:	learn: 6731473.7424716	total: 166ms	remaining: 377ms
306:	learn: 6727038.9939715	total: 167ms	remaining: 376ms
307:	learn: 6720486.8629373	total: 167ms	remaining: 376ms
308:	learn: 6717732.6838221	total: 168ms	remaining: 376ms
309:	learn: 6713528.3999476	total: 169ms	remaining: 375ms
310:	learn: 6705539.7806092	total: 169ms	remaining: 375ms
311:	learn: 6702385.9990807	total: 170ms	remaining: 374ms
312:	learn: 6699724.0485852	total: 170ms	remaining: 374ms
313:	learn: 6691850.7147005	total: 171ms	remaining: 373ms
314:	learn: 6687633.0021209	total: 172ms	remaining: 373ms
315:	learn: 6679896.5133781	total: 172ms	remaining: 373ms
316:	learn: 6676645.8558572	total: 173ms	remaining: 372ms
317:	learn: 6674138.4828669	total: 174ms	remaining: 373ms
318:	learn: 6666546.6513697	total: 174ms	remaining: 372ms
319:	learn: 6659569.6150647	total: 175ms	remaining: 372ms
320:	learn: 6656949.4803020	total: 176ms	remaining: 372ms
321:	learn: 6654536.8068083	total: 176ms	remaining: 371ms
322:	learn: 6650665.9525790	total: 177ms	remaining: 371ms
323:	learn: 6645682.2059305	total: 178ms	remaining: 370ms
324:	learn: 6641767.8057178	total: 178ms	remaining: 370ms
325:	learn: 6632185.9009765	total: 179ms	remaining: 370ms
326:	learn: 6629382.7509349	total: 179ms	remaining: 369ms
327:	learn: 6626882.6817705	total: 180ms	remaining: 369ms
328:	learn: 6621236.8124364	total: 181ms	remaining: 369ms
329:	learn: 6616004.2427652	total: 181ms	remaining: 368ms
330:	learn: 6610955.9865001	total: 182ms	remaining: 368ms
331:	learn: 6596912.8739719	total: 183ms	remaining: 367ms
332:	learn: 6594387.2436590	total: 184ms	remaining: 368ms
333:	learn: 6587252.1635709	total: 184ms	remaining: 368ms
334:	learn: 6583592.6328301	total: 185ms	remaining: 367ms
335:	learn: 6578423.5227484	total: 186ms	remaining: 367ms
336:	learn: 6574837.5111771	total: 186ms	remaining: 367ms
337:	learn: 6557665.8700760	total: 187ms	remaining: 366ms
338:	learn: 6549784.9120373	total: 188ms	remaining: 366ms
339:	learn: 6547395.9338910	total: 188ms	remaining: 366ms
340:	learn: 6544774.8023155	total: 189ms	remaining: 365ms
341:	learn: 6537825.1883846	total: 190ms	remaining: 365ms